name: Update Gas Prices JSON

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # Updated to latest requirement
          
      - name: Install dependencies
        run: |
          pip install py-gasbuddy
          
      - name: Run Scraper
        run: python scripts/scraper.py
        
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/gas_prices.json
          git commit -m "Update gas_prices.json" || echo "No changes"
          git push
